# 日志
spring:
  elasticsearch:
    uris: http://172.16.90.231:9200
  datasource:
    username: search_admin
    password: search_admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.16.113.253:5432/search
    druid:
      filters: stat,wall
      maxActive: 5
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select version()
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


logging:
  level:
    root: debug

# endpoint
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
      base-path: /actuator
  server:
    port: 8081



search:
  config:
    hosts:
      - "172.16.90.231:9200"

#spring:
#  security:
#    user:
#      name: admin
#      password: 123456
#      roles: SUPERADMIN

es:
  index:
    snapshot:
      repositoryLocation: /backup/es_backup
      repositoryName: es_snapshot_repo



#mybatisplus 配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/**/*Mapper.xml
#  global-config:
#    db-config:
#      logic-delete-field: deleteFlag # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 #逻辑删除
#      logic-not-delete-value: 0 #逻辑未删除
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

arthas:
  appName: ${spring.application.name}
  tunnel-server: ws://172.16.90.11:7777/ws