
# 日志
logging:
  level:
    root: info

# endpoint
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
      base-path: /actuator
  server:
    port: 8081

server:
  port: 8080

#spring:
#  security:
#    user:
#      name: admin
#      password: 123456
#      roles: SUPERADMIN
spring:
  main:
    allow-circular-references: true
  elasticsearch:
    uris: http://172.16.90.231:9200
  datasource:
    username: search_admin
    password: search_admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.16.113.253:5432/search
    druid:
      filters: stat,wall
      maxActive: 5
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select version()
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000



#mybatisplus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
